version: "3.2"
services:
  slack:
    image: php:7.2-rc-cli
    ports:
      - 2001:2001/tcp
    tty: true
    environment:
      # 請參考 slack
      - slackUrl=''
      - slackChannel="#general"
      - slackBotName="bot"
      - slackBotIcon=":ghost:"
    container_name: slack
    volumes:
      - ./slack.php:/slack/slack.php
    working_dir: /slack
    command: php -S 0.0.0.0:2000 # curl -X POST http://localhost:2001/slack.php